### ISSUE TITLE
Noctilucent won't work because of inputFormat

### ISSUE THREAD

**Issue by iph** [iph/noctilucent#110]
Most recent code version is blowing up:

```
./target/release/noctilucent ~/beta-iad-fdn-template.yml ~/noct_output
thread 'main' panicked at 'Mismatch between definition and access of `inputFormat`. Could not downcast to TypeId { t: 9919015677752515272 }, need to downcast to TypeId { t: 3422896439451675198 }
', /home/audettem/.cargo/registry/src/github.com-1ecc6299db9ec823/clap_builder-4.2.4/src/parser/error.rs:32:9
stack backtrace:
   0:     0x56210f469ca0 - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56210f469ca0 - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56210f469ca0 - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x56210f469ca0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56210f3fb1be - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x56210f4464f4 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x56210f46b1a7 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x56210f46b1a7 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x56210f46af45 - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x56210f46b52a - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x56210f46b52a - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:     0x56210f46b354 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:     0x56210f46b2b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x56210f46b2a1 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:     0x56210f39d032 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:     0x56210f3acb68 - clap_builder::parser::matches::arg_matches::ArgMatches::get_one::h656f7308b6e353a0
  16:     0x56210f3b7b81 - noctilucent::main::h615327d183ce36c5
  17:     0x56210f3ae033 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha308490c506925fd
  18:     0x56210f3b9f70 - main
  19:     0x7f1cc168a13a - __libc_start_main
  20:     0x56210f3a773a - _start
  21:                0x0 - <unknown>
```

Also doesn't work when specifying inputFormat:

```
./target/release/noctilucent ~/beta-iad-fdn-template.yml ~/noct_output --input-format=yaml
thread 'main' panicked at 'Mismatch between definition and access of `inputFormat`. Could not downcast to TypeId { t: 9919015677752515272 }, need to downcast to TypeId { t: 3422896439451675198 }
', /home/audettem/.cargo/registry/src/github.com-1ecc6299db9ec823/clap_builder-4.2.4/src/parser/error.rs:32:9
stack backtrace:
   0:     0x55a318ee8ca0 - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a318ee8ca0 - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
```

**Comment by iph** [comment]
I'm just going to nuke inputFormat, even though it's backwards incompatible -- the feature has only been around for a month and is deprecated anyways.
